AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function/handler.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 29
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: any
            TimeoutInMillis: 29000
            PayloadFormatVersion: '2.0'
Outputs:
  WebEndpoint:
    Value: "!Sub
      'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Pr\
      od/'"
